[project]
name = "animal-advice-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "py-eureka-client>=0.11.13",
    "uvicorn>=0.34.2",
]
