server:
  port: 8082
s3:
  accessKeyId: KM2S7GR01BUER3FKDN0U
  secretAccessKey: MXG3weJGL25Uk3RLkktsZNt1AXwG7pI6tiq7FMnR
  minioUrl: https://s3.twcstorage.ru
  region: ru-1
  bucket: 242358d3-goods-bucket

spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: db-event
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://users_db/users_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/