server:
  port: 8084

spring:
  application:
    name: auth-service
  public-urls:
    - "/api/auth/**"
    - "/api/password/**"
    - "/api/token/**"
    - "/api/activate-account"
    - "/v3/api-docs/**"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/swagger-resources/**"
    - "/webjars/**"
    - "/v2/api-docs"
    - "/v2/api-docs/**"
    - "/webjars/swagger-ui/**"
    - "/v3/api-docs"
    - "/swagger-ui/index.html"
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.value.default.type: ru.doedating.userservice.dto.UserCreatedEvent

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://auth_db/auth_db
    username: postgres
    password: postgres
  jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: false
      properties:
        hibernate:
          format_sql: true
      database: postgresql
  mail:
    host: smtp.yandex.ru
    port: 465
    username: "doedating@yandex.ru"
    password: "mrzvlstuwsgocmue"
    test-connection: true
    protocol: smtps
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection timeout: 5000
        timeout: 3000
        write timeout: 5000
  security:
    jwt:
      secret-key: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
      expiration: 3600
      refresh-expiration: 604800
    oauth2:
      client:
        registration:
          vk:
            client-name: vk
            client-id: 52916407
            client-secret: pDQj5xjxpfyxwYiqpXwV
            redirect-uri: http://localhost/api/auth/login/oauth2/code/vk
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - email
              - profile
            provider: vk
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=199
            user-name-attribute: response

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

mailing:
  activation-url: http://localhost:4200/activate-accout
  email-address-sender: "doedating@yandex.ru"
  activation-token-expiration: 3600
